FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends coreutils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY exr.sh ./exr.sh
RUN chmod +x ./exr.sh

VOLUME /app/shared_volume

ENTRYPOINT ["./exr.sh"]
